### ISSUE TITLE
Dashboard errors

### ISSUE THREAD

**Issue by FriiZoLoGYy** [SirHoDo/PeepyLlama#1]
When starting bot and visiting dashboard each time greeted with this error

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at ServerResponse.header (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\response.js:170:12)
    at done (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\response.js:1008:10)
    at tryHandleCache (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\ejs\lib\ejs.js:278:5)
    at View.exports.renderFile [as engine] (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\ejs\lib\ejs.js:489:10)
    at View.render (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\response.js:1012:7)
    at renderTemplate (C:\Users\zunet\Desktop\PeepyLlama-main\dashboard\dashboard.js:59:9)
    at C:\Users\zunet\Desktop\PeepyLlama-main\dashboard\dashboard.js:204:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
UNHANDLED REJECTION!
{ type: 0, errmsg: 'User doesnt exist' }
Promise { <rejected> { type: 0, errmsg: 'User doesnt exist' } }

**Comment by SirHoDo** [comment]
> When starting bot and visiting dashboard each time greeted with this error
> 
> 
> 
> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
> 
>     at new NodeError (node:internal/errors:371:5)
> 
>     at ServerResponse.setHeader (node:_http_outgoing:573:11)
> 
>     at ServerResponse.header (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\response.js:771:10)
> 
>     at ServerResponse.send (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\response.js:170:12)
> 
>     at done (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\response.js:1008:10)
> 
>     at tryHandleCache (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\ejs\lib\ejs.js:278:5)
> 
>     at View.exports.renderFile [as engine] (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\ejs\lib\ejs.js:489:10)
> 
>     at View.render (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\view.js:135:8)
> 
>     at tryRender (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\application.js:640:10)
> 
>     at Function.render (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\application.js:592:3)
> 
>     at ServerResponse.render (C:\Users\zunet\Desktop\PeepyLlama-main\node_modules\express\lib\response.js:1012:7)
> 
>     at renderTemplate (C:\Users\zunet\Desktop\PeepyLlama-main\dashboard\dashboard.js:59:9)
> 
>     at C:\Users\zunet\Desktop\PeepyLlama-main\dashboard\dashboard.js:204:5
> 
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> UNHANDLED REJECTION!
> 
> { type: 0, errmsg: 'User doesnt exist' }
> 
> Promise { <rejected> { type: 0, errmsg: 'User doesnt exist' } }

Hey, are you attempting to visit a user profile or the index of the dashboard?

**Comment by FriiZoLoGYy** [comment]
user profile. I can get main front end up
 checking mongo it only saves a db called json with nothing in it as well

**Comment by FriiZoLoGYy** [comment]
along with dashboard trying to ping the bot, it returns this

UNHANDLED REJECTION!
TypeError: Cannot read property 'messagesSent' of undefined
    at MessageCreate.run (C:\Users\zunet\Desktop\PeepyLlama-main\src\events\bot\messageCreate.js:29:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Promise {
  <rejected> TypeError: Cannot read property 'messagesSent' of undefined
      at MessageCreate.run (C:\Users\zunet\Desktop\PeepyLlama-main\src\events\bot\messageCreate.js:29:30)       
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by SirHoDo** [comment]
> along with dashboard trying to ping the bot, it returns this
> 
> 
> 
> UNHANDLED REJECTION!
> 
> TypeError: Cannot read property 'messagesSent' of undefined
> 
>     at MessageCreate.run (C:\Users\zunet\Desktop\PeepyLlama-main\src\events\bot\messageCreate.js:29:30)
> 
>     at runMicrotasks (<anonymous>)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> Promise {
> 
>   <rejected> TypeError: Cannot read property 'messagesSent' of undefined
> 
>       at MessageCreate.run (C:\Users\zunet\Desktop\PeepyLlama-main\src\events\bot\messageCreate.js:29:30)       
> 
>       at runMicrotasks (<anonymous>)
> 
>       at processTicksAndRejections (node:internal/process/task_queues:96:5)

Message me on Discord Ethan Primmer#1089

**Comment by FriiZoLoGYy** [comment]
I sent you a request

> > along with dashboard trying to ping the bot, it returns this
> > UNHANDLED REJECTION!
> > TypeError: Cannot read property 'messagesSent' of undefined
> > ```
> > at MessageCreate.run (C:\Users\zunet\Desktop\PeepyLlama-main\src\events\bot\messageCreate.js:29:30)
> > 
> > at runMicrotasks (<anonymous>)
> > 
> > at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Promise {
> >  TypeError: Cannot read property 'messagesSent' of undefined
> > ```
> >   at MessageCreate.run (C:\Users\zunet\Desktop\PeepyLlama-main\src\events\bot\messageCreate.js:29:30)       
> > 
> >   at runMicrotasks (<anonymous>)
> > 
> >   at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > ```
> 
> Message me on Discord Ethan Primmer#1089

i sent you a request then

**Comment by SirHoDo** [comment]
Issue closed.
Resolved MessagesSent issue (removed)

And User Profiles must contain a valid user id (example)
https://peepy.info/user/456062221710131210
